# See PostgresConf's FromJSON instance for available fields
userDataDir: ".local/share/babel-cards"
database:
  connInfo:
    connectionString: 'babel-cards.sqlite'
    walEnabled: true
    fkEnabled: true
  poolsize: 1
